service: payment
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1

functions:
  createCompany:
    handler: handler.createCompany
    events:
      - httpApi:
          path: /company
          method: post
  createInvoice:
    handler: handler.createInvoice
    events:
      - httpApi:
          path: /invoice
          method: post
  getPayment:
    handler: handler.getPayment
    events:
      - httpApi:
          path: /payment
          method: get
  getInternalSupplier:
    handler: handler.getInternalSupplier
    events:
      - httpApi:
          path: /internalsupplier
          method: get