service: payment
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1

functions:
  createCompany:
    handler: handler.createCompany
    events:
      - httpApi:
          path: /company
          method: post
