service: supplier
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1

functions:
  getCompanyDelta:
    handler: handler.getCompanyDelta
    events:
      - httpApi:
          path: /company/delta
          method: get
  getInvoiceDelta:
    handler: handler.getInvoiceDelta
    events:
      - httpApi:
          path: /invoice/delta
          method: get
  updatePayment:
    handler: handler.updatePayment
    events:
      - httpApi:
          path: /invoice/payment
          method: put
  createInternalSupplier:
    handler: handler.createInternalSupplier
    events:
      - httpApi:
          path: /internalsupplier
          method: post
